export const SHOW_LOADING = 'SHOW_LOADING'
export const HIDE_LOADING = 'HIDE_LOADING'

export const GET_HOME_CONFIG_SUCCESS = 'GET_HOME_CONFIG_SUCCESS'
export const GET_HOME_DATA_SUCCESS = 'GET_HOME_DATA_SUCCESS'
